name: Deploy to Digital Ocean
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs: 
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://docs.dworac.com
    steps:
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.1.5
        with:
          app_name: dworac-docs
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
